# Generated by Django 5.2 on 2025-05-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='imagem',
        ),
    ]
