# Generated by Django 4.2.22 on 2026-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0006_alter_loggeracaoedital_id_alter_notificacao_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroedital',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
