# Generated by Django 4.2.22 on 2026-06-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas', models.JSONField(help_text='Mapa {numero_questao: alternativa}', verbose_name='Respostas')),
                ('pontuacao', models.PositiveSmallIntegerField(verbose_name='Pontuação')),
                ('total_questoes', models.PositiveSmallIntegerField(verbose_name='Total de questões')),
                ('criticas_sugestoes', models.TextField(blank=True, verbose_name='Críticas e sugestões')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Respondido em')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_questionario', to='educacional.participante')),
            ],
            options={
                'verbose_name': 'Resposta de questionário',
                'verbose_name_plural': 'Respostas de questionários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
