# Generated by Django 5.1.7 on 2025-04-02 00:57

import crr.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_crr', models.IntegerField(max_length=10)),
                ('placa_chassi', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use: AAA-1234, AAA-1A23 ou 17 caracteres alfanuméricos', regex='^([A-Z]{3}-\\d{4}|[A-Z]{3}-\\d[A-Z]\\d{2}|[A-Za-z0-9]{17})$')])),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('especie', models.CharField(choices=[('passageiro', 'Passageiro'), ('carga', 'Carga'), ('misto', 'Misto'), ('tracao', 'Tração'), ('colecao', 'Coleção'), ('especial', 'Especial')], max_length=20)),
                ('categoria', models.CharField(choices=[('oficial', 'Oficial'), ('particular', 'Particular'), ('aluguel', 'Aluguel')], max_length=20)),
                ('uf_veiculo', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], default='SP', max_length=6)),
                ('municipio_veiculo', models.CharField(max_length=25)),
                ('local_remocao', models.CharField(max_length=100)),
                ('data_remocao', models.DateField()),
                ('hora_remocao', models.TimeField()),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('agente_autuador', models.IntegerField(max_length=10)),
                ('status', models.CharField(choices=[('retido', 'Retido'), ('liberado', 'Liberado')], default='retido', help_text='Status atual do veículo (Retido/Liberado)', max_length=10)),
                ('habilitacao_condutor', models.CharField(blank=True, max_length=11)),
                ('uf_cnh', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], default='SP', max_length=6)),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('nome_condutor', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ait', models.CharField(blank=True, help_text='Formato: Letra + 2 números + hífen + 7 números (Ex: A12-0123456)', max_length=10, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use: A12-0123456', regex='^[A-Z]\\d{2}-\\d{7}$')], verbose_name='Código de AIT')),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ait', to='crr.crr')),
            ],
        ),
        migrations.CreateModel(
            name='Enquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquadramento', models.IntegerField(blank=True, max_length=5)),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquadramento', to='crr.crr')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('data_postagem', models.DateField()),
                ('numero_controle', models.CharField(max_length=7, unique=True)),
                ('descricao_infracao', models.CharField(blank=True, max_length=100)),
                ('amparo_legal', models.CharField(max_length=25)),
                ('prazo_leilao', models.DateField()),
                ('destinatario', models.CharField(max_length=25)),
                ('endereco', models.CharField(max_length=25)),
                ('numero', models.CharField(max_length=6)),
                ('complemento', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(max_length=25)),
                ('cidade_destinatario', models.CharField(max_length=25)),
                ('uf_destinatario', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], max_length=6)),
                ('cep', models.CharField(help_text='Formato: 11600-000', max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 11600-000', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('imagem', models.ImageField(blank=True, upload_to=crr.models.upload_path, verbose_name='Imagem da Notificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('crr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao', to='crr.crr')),
            ],
        ),
    ]
