# Generated by Django 5.2 on 2025-04-06 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arrendatario', models.CharField(blank=True, max_length=25)),
                ('cnpj_arrendatario', models.CharField(blank=True, max_length=14)),
                ('endereco_arrendatario', models.CharField(blank=True, max_length=25)),
                ('numero_arrendatario', models.CharField(blank=True, max_length=6)),
                ('complemento_arrendatario', models.CharField(blank=True, max_length=10)),
                ('bairro_arrendatario', models.CharField(blank=True, max_length=25)),
                ('uf_arrendatario', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], max_length=6)),
                ('cep_arrendatario', models.CharField(max_length=9, verbose_name='CEP')),
                ('cidade_arrendatario', models.CharField(blank=True, max_length=25)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Crr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_crr', models.CharField(max_length=10, unique=True, verbose_name='número do crr')),
                ('placa_chassi', models.CharField(blank=True, max_length=17, verbose_name='placa~chassi')),
                ('marca', models.CharField(blank=True, max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=20)),
                ('especie', models.CharField(blank=True, choices=[('passageiro', 'Passageiro'), ('carga', 'Carga'), ('misto', 'Misto'), ('tracao', 'Tração'), ('colecao', 'Coleção'), ('especial', 'Especial')], max_length=20)),
                ('categoria', models.CharField(blank=True, choices=[('oficial', 'Oficial'), ('particular', 'Particular'), ('aluguel', 'Aluguel')], max_length=20)),
                ('uf_veiculo', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], default='SP', max_length=6)),
                ('municipio_veiculo', models.CharField(max_length=25)),
                ('local_remocao', models.CharField(max_length=100)),
                ('data_remocao', models.DateField()),
                ('hora_remocao', models.TimeField()),
                ('observacao', models.CharField(blank=True, default='abandonado', max_length=100)),
                ('agente_autuador', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('retido', 'Retido'), ('liberado', 'Liberado')], default='retido', help_text='Status atual do veículo (Retido/Liberado)', max_length=10)),
                ('habilitacao_condutor', models.CharField(blank=True, max_length=11)),
                ('uf_cnh', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], default='SP', max_length=6)),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('nome_condutor', models.CharField(blank=True, max_length=50)),
                ('not_gerada', models.BooleanField(default=False)),
                ('edital_emitido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('arrendatario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='crr.arrendatario')),
            ],
        ),
        migrations.CreateModel(
            name='Ait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ait', models.CharField(blank=True, max_length=11, verbose_name='Código de AIT')),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ait', to='crr.crr')),
            ],
        ),
        migrations.CreateModel(
            name='Enquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquadramento', models.CharField(blank=True, max_length=5)),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquadramento', to='crr.crr')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('data_postagem', models.DateField()),
                ('numero_controle', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('descricao_infracao', models.CharField(blank=True, max_length=100)),
                ('amparo_legal', models.CharField(max_length=25)),
                ('prazo_leilao', models.DateField()),
                ('destinatario', models.CharField(max_length=25)),
                ('endereco', models.CharField(max_length=25)),
                ('numero', models.CharField(max_length=6)),
                ('complemento', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(max_length=25)),
                ('cidade_destinatario', models.CharField(max_length=25)),
                ('uf_destinatario', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], max_length=6)),
                ('cep', models.CharField(help_text='Formato: 11600-000', max_length=9, verbose_name='CEP')),
                ('imagem', models.ImageField(blank=True, upload_to='notifcacoes/', verbose_name='Imagem da Notificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('crr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao', to='crr.crr')),
            ],
        ),
    ]
