# Generated by Django 5.2 on 2025-04-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_crr', models.PositiveIntegerField(unique=True, verbose_name='número do crr')),
                ('placa_chassi', models.CharField(blank=True, max_length=17, verbose_name='placa/chassi')),
                ('marca', models.CharField(blank=True, max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=20)),
                ('especie', models.CharField(blank=True, choices=[('passageiro', 'Passageiro'), ('carga', 'Carga'), ('misto', 'Misto'), ('tracao', 'Tração'), ('colecao', 'Coleção'), ('especial', 'Especial')], max_length=20, verbose_name='espécie')),
                ('categoria', models.CharField(blank=True, choices=[('oficial', 'Oficial'), ('particular', 'Particular'), ('aluguel', 'Aluguel')], max_length=20)),
                ('uf_veiculo', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], default='SP', max_length=6, verbose_name='UF do veículo')),
                ('municipio_veiculo', models.CharField(max_length=25, verbose_name='Município do veículo')),
                ('local_remocao', models.CharField(max_length=100, verbose_name='Local da Remoção')),
                ('data_remocao', models.DateField(verbose_name='Data da remoção')),
                ('hora_remocao', models.TimeField(verbose_name='Hora da remoção')),
                ('observacao', models.CharField(blank=True, max_length=100, verbose_name='Observação')),
                ('agente_autuador', models.CharField(max_length=10, verbose_name='Agente autuador')),
                ('status', models.CharField(choices=[('retido', 'Retido'), ('liberado', 'Liberado')], default='retido', help_text='Status atual do veículo (Retido/Liberado)', max_length=8)),
                ('habilitacao_condutor', models.CharField(blank=True, max_length=11, verbose_name='Habilitação do condutor')),
                ('uf_cnh', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], default='SP', max_length=6, verbose_name='UF da CNH')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('nome_condutor', models.CharField(blank=True, max_length=50, verbose_name='Nome do condutor')),
                ('not_gerada', models.BooleanField(default=False, verbose_name='Status da Notificação')),
                ('edital_emitido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRR',
                'verbose_name_plural': 'CRRs',
            },
        ),
        migrations.CreateModel(
            name='NumeroEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arrendatario', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Nome do arrendatário')),
                ('cnpj_arrendatario', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('endereco_arrendatario', models.CharField(blank=True, max_length=25, verbose_name='Endereço')),
                ('numero_arrendatario', models.CharField(blank=True, max_length=6, verbose_name='número')),
                ('complemento_arrendatario', models.CharField(blank=True, max_length=10, verbose_name='Complemento')),
                ('bairro_arrendatario', models.CharField(blank=True, max_length=25, verbose_name='Bairro')),
                ('cidade_arrendatario', models.CharField(blank=True, max_length=25, verbose_name='Cidade')),
                ('uf_arrendatario', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], max_length=6, verbose_name='UF')),
                ('cep_arrendatario', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Arrendatário',
                'verbose_name_plural': 'Arrendatários',
            },
        ),
        migrations.CreateModel(
            name='TabelaEnquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('amparo_legal', models.CharField(max_length=100)),
                ('descricao_infracao', models.CharField(max_length=500, verbose_name='Descrição da informação')),
            ],
            options={
                'verbose_name': 'Enquadramento',
                'verbose_name_plural': 'Enquadramentos',
            },
        ),
        migrations.CreateModel(
            name='Ait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ait', models.CharField(blank=True, max_length=11, verbose_name='Código de AIT')),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ait', to='crr.crr')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de emissão')),
                ('data_postagem', models.DateField(verbose_name='Data de postagem')),
                ('numero_controle', models.PositiveIntegerField(unique=True, verbose_name='Numero de controle')),
                ('prazo_leilao', models.DateField(verbose_name='Prazo p/ leilão')),
                ('destinatario', models.CharField(max_length=50, verbose_name='destinatário')),
                ('endereco', models.CharField(max_length=50, verbose_name='endereço')),
                ('numero', models.CharField(max_length=6, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=10, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=25, verbose_name='Bairro')),
                ('cidade_destinatario', models.CharField(max_length=25, verbose_name='Cidade do destinatário')),
                ('uf_destinatario', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], max_length=6, verbose_name='UF do destinatário')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('imagem', models.ImageField(blank=True, upload_to='notificacoes/', verbose_name='Imagem da Notificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('crr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao', to='crr.crr', verbose_name='CRR')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendatarios', to='crr.crr')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crr.tabelaarrendatario', verbose_name='Arrendatário')),
            ],
            options={
                'verbose_name': 'Arrendatário',
                'verbose_name_plural': 'Arrendatários',
            },
        ),
        migrations.CreateModel(
            name='Enquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquadramentos', to='crr.crr')),
                ('enquadramento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crr.tabelaenquadramento', verbose_name='Enquadramento')),
            ],
        ),
    ]
