# Generated by Django 5.2.1 on 2025-05-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='municipioVeiculo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Município do veículo'),
        ),
    ]
