# Generated by Django 5.1.7 on 2025-04-02 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ait',
            name='ait',
            field=models.CharField(blank=True, help_text='Formato: Letra + 2 números + hífen + 7 números (Ex: A12-0123456)', max_length=11, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use: A12-0123456', regex='^[A-Z]\\d{2}-\\d{7}$')], verbose_name='Código de AIT'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='agente_autuador',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='crr',
            name='numero_crr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enquadramento',
            name='enquadramento',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
