# Generated by Django 5.2.1 on 2025-05-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemcrr',
            name='nomeArquivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo'),
        ),
        migrations.AddField(
            model_name='imagemcrr',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Imagem (S3 via API)'),
        ),
    ]
