# Generated by Django 5.1.8 on 2025-04-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='numero_controle',
            field=models.IntegerField(max_length=7, unique=True),
        ),
    ]
