# Generated by Django 5.2 on 2025-04-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='notificacoes/', verbose_name='Imagem da Notificação'),
        ),
    ]
