# Generated by Django 5.2 on 2025-04-25 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crr',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crrs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crr',
            name='marca',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='crr',
            name='modelo',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='crr',
            name='municipio_veiculo',
            field=models.CharField(blank=True, max_length=25, verbose_name='Município do veículo'),
        ),
    ]
