# Generated by Django 5.2 on 2025-04-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='destinatario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='endereco',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='bairro_arrendatario',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='cep_arrendatario',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='cidade_arrendatario',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='cnpj_arrendatario',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='endereco_arrendatario',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='nome_arrendatario',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='numero_arrendatario',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='uf_arrendatario',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], max_length=6),
        ),
    ]
