# Generated by Django 5.2 on 2025-04-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0002_alter_notificacao_numero_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='crr',
            name='not_gerada',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='crr',
            name='observacao',
            field=models.CharField(blank=True, default='abandonado', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='notifcacoes/', verbose_name='Imagem da Notificação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='numero_controle',
            field=models.IntegerField(unique=True),
        ),
    ]
