# Generated by Django 5.2 on 2025-04-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0002_alter_notificacao_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AlterModelOptions(
            name='tabelaarrendatario',
            options={'verbose_name': 'Arrendatário', 'verbose_name_plural': 'Arrendatários'},
        ),
        migrations.AlterModelOptions(
            name='tabelaenquadramento',
            options={'verbose_name': 'Enquadramento', 'verbose_name_plural': 'Enquadramentos'},
        ),
        migrations.AlterField(
            model_name='crr',
            name='agente_autuador',
            field=models.CharField(max_length=10, verbose_name='Agente autuador'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='data_remocao',
            field=models.DateField(verbose_name='Data da remoção'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='especie',
            field=models.CharField(blank=True, choices=[('passageiro', 'Passageiro'), ('carga', 'Carga'), ('misto', 'Misto'), ('tracao', 'Tração'), ('colecao', 'Coleção'), ('especial', 'Especial')], max_length=20, verbose_name='espécie'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='habilitacao_condutor',
            field=models.CharField(blank=True, max_length=11, verbose_name='Habilitação do condutor'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='hora_remocao',
            field=models.TimeField(verbose_name='Hora da remoção'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='local_remocao',
            field=models.CharField(max_length=100, verbose_name='Local da Remoção'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='municipio_veiculo',
            field=models.CharField(max_length=25, verbose_name='Município do veículo'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='nome_condutor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome do condutor'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='not_gerada',
            field=models.BooleanField(default=False, verbose_name='Status da Notificação'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='numero_crr',
            field=models.PositiveIntegerField(unique=True, verbose_name='número do crr'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='status',
            field=models.CharField(choices=[('retido', 'Retido'), ('liberado', 'Liberado')], default='retido', help_text='Status atual do veículo (Retido/Liberado)', max_length=8),
        ),
        migrations.AlterField(
            model_name='crr',
            name='uf_cnh',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], default='SP', max_length=6, verbose_name='UF da CNH'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='uf_veiculo',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], default='SP', max_length=6, verbose_name='UF do veículo'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='bairro',
            field=models.CharField(max_length=25, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='cidade_destinatario',
            field=models.CharField(max_length=25, verbose_name='Cidade do destinatário'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='complemento',
            field=models.CharField(blank=True, max_length=10, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='crr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao', to='crr.crr', verbose_name='CRR'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_emissao',
            field=models.DateField(verbose_name='Data de emissão'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_postagem',
            field=models.DateField(verbose_name='Data de postagem'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='destinatario',
            field=models.CharField(max_length=50, verbose_name='destinatário'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='numero',
            field=models.CharField(max_length=6, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='numero_controle',
            field=models.PositiveIntegerField(unique=True, verbose_name='Numero de controle'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='prazo_leilao',
            field=models.DateField(verbose_name='Prazo p/ leilão'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='uf_destinatario',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], max_length=6, verbose_name='UF do destinatário'),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='bairro_arrendatario',
            field=models.CharField(blank=True, max_length=25, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='cidade_arrendatario',
            field=models.CharField(blank=True, max_length=25, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='cnpj_arrendatario',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='complemento_arrendatario',
            field=models.CharField(blank=True, max_length=10, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='endereco_arrendatario',
            field=models.CharField(blank=True, max_length=25, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='nome_arrendatario',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='Nome do arrendatário'),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='numero_arrendatario',
            field=models.CharField(blank=True, max_length=6, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='uf_arrendatario',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], max_length=6, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='tabelaenquadramento',
            name='codigo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tabelaenquadramento',
            name='descricao_infracao',
            field=models.CharField(max_length=500, verbose_name='Descrição da informação'),
        ),
    ]
