# Generated by Django 5.2 on 2025-04-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0002_crr_usuario_alter_crr_marca_alter_crr_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crr',
            name='numero_crr',
            field=models.CharField(max_length=10, unique=True, verbose_name='número do crr'),
        ),
    ]
