# Generated by Django 5.2.1 on 2025-05-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0002_alter_veiculo_chassi_alter_veiculo_municipioveiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crr',
            name='matriculaAgente',
            field=models.CharField(max_length=10),
        ),
    ]
