# Generated by Django 5.2.1 on 2025-05-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0002_imagemcrr_nomearquivo_imagemcrr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemcrr',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL da Imagem (S3 via API)'),
        ),
    ]
