# Generated by Django 5.2 on 2025-04-15 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0002_alter_notificacao_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaEnquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('amparo_legal', models.CharField(max_length=100)),
                ('descricao_infracao', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='enquadramento',
            options={},
        ),
        migrations.AlterField(
            model_name='enquadramento',
            name='crr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquadramentos', to='crr.crr'),
        ),
        migrations.AlterField(
            model_name='enquadramento',
            name='enquadramento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crr.tabelaenquadramento', verbose_name='Enquadramento'),
        ),
    ]
