# Generated by Django 5.2.1 on 2025-05-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0003_alter_imagemcrr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemcrr',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='crr/', verbose_name='Imagem (upload via Admin)'),
        ),
        migrations.AlterField(
            model_name='imagemcrr',
            name='nomeArquivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagemcrr',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
