# Generated by Django 5.2 on 2025-04-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0003_crr_not_gerada_alter_crr_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crr',
            name='not_gerada',
            field=models.BooleanField(default=False),
        ),
    ]
