# Generated by Django 5.2 on 2025-04-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0003_tabelaenquadramento_alter_enquadramento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='amparo_legal',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='descricao_infracao',
        ),
    ]
