# Generated by Django 5.2 on 2025-04-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0003_alter_crr_numero_crr'),
    ]

    operations = [
        migrations.AddField(
            model_name='crr',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Assinatura do Condutor'),
        ),
    ]
