# Generated by Django 5.2 on 2025-04-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0004_alter_crr_not_gerada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crr',
            name='not_gerada',
            field=models.BooleanField(default=True),
        ),
    ]
