# Generated by Django 5.2.1 on 2025-05-28 16:38

import crr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0004_alter_imagemcrr_imagem_alter_imagemcrr_nomearquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condutor',
            name='ufCnh',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('OUTROS', 'OUTROS')], max_length=6, verbose_name='UF da CNH'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='encarregado',
            field=models.CharField(blank=True, max_length=50, verbose_name='encarregado do guincho'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='numeroCrr',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='número do crr'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='imagemcrr',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=crr.models.upload_path, verbose_name='Imagem (upload via Admin)'),
        ),
        migrations.AlterField(
            model_name='tabelaarrendatario',
            name='uf_arrendatario',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('OUTROS', 'OUTROS')], max_length=6, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ufVeiculo',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('OUTROS', 'OUTROS')], max_length=6, verbose_name='UF do veículo'),
        ),
    ]
