# Generated by Django 5.2 on 2025-04-30 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0005_alter_crr_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crr',
            name='usuario',
        ),
        migrations.CreateModel(
            name='AgenteAutuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do Agente')),
                ('matricula', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Matrícula')),
                ('orgao', models.CharField(choices=[('detraf', 'DETRAF'), ('gcm', 'GCM'), ('pm', 'PM')], max_length=6, verbose_name='Órgão')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente_autuador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='crr',
            name='agente_autuador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crrs', to='crr.agenteautuador'),
        ),
    ]
