# Generated by Django 5.2 on 2025-04-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0005_alter_crr_not_gerada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='numero_controle',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
