# Generated by Django 5.2 on 2025-04-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0006_remove_crr_usuario_agenteautuador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteautuador',
            name='matricula',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
