# Generated by Django 5.2 on 2025-04-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0006_alter_notificacao_numero_controle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crr',
            name='not_gerada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='numero_controle',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
