# Generated by Django 5.2 on 2025-04-30 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0007_alter_agenteautuador_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteautuador',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agenteautuador',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Agente'),
        ),
        migrations.AlterField(
            model_name='agenteautuador',
            name='orgao',
            field=models.CharField(blank=True, choices=[('detraf', 'DETRAF'), ('gcm', 'GCM'), ('pm', 'PM')], max_length=6, null=True, verbose_name='Órgão'),
        ),
        migrations.AlterField(
            model_name='agenteautuador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_autuador', to=settings.AUTH_USER_MODEL),
        ),
    ]
