# Generated by Django 5.2 on 2025-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0007_alter_crr_not_gerada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crr',
            name='edital_emitido',
            field=models.BooleanField(default=False),
        ),
    ]
