# Generated by Django 5.2 on 2025-05-01 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0008_alter_agenteautuador_matricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitacao_condutor', models.CharField(blank=True, max_length=11, verbose_name='Habilitação do condutor')),
                ('uf_cnh', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('OUTROS', 'Outros')], default='SP', max_length=6, verbose_name='UF da CNH')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('nome_condutor', models.CharField(blank=True, max_length=50, verbose_name='Nome do condutor')),
                ('assinatura_condutor', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Assinatura do Condutor')),
            ],
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='crr',
        ),
        migrations.DeleteModel(
            name='NumeroEdital',
        ),
        migrations.RemoveField(
            model_name='agenteautuador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='crr',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='crr',
            name='habilitacao_condutor',
        ),
        migrations.RemoveField(
            model_name='crr',
            name='nome_condutor',
        ),
        migrations.RemoveField(
            model_name='crr',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='crr',
            name='uf_cnh',
        ),
        migrations.AddField(
            model_name='agenteautuador',
            name='assinatura_agente',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Assinatura do Condutor'),
        ),
        migrations.AddField(
            model_name='agenteautuador',
            name='nome_agente',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome do Agente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crr',
            name='matricula_agente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agenteautuador',
            name='matricula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='crr',
            name='condutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crrs', to='crr.condutor'),
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
