# Generated by Django 5.2 on 2025-05-01 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0009_condutor_remove_notificacao_crr_delete_numeroedital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteautuador',
            name='assinatura_agente',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Assinatura do Agente'),
        ),
        migrations.AlterField(
            model_name='agenteautuador',
            name='orgao',
            field=models.CharField(choices=[('detraf', 'DETRAF'), ('gcm', 'GCM'), ('pm', 'PM')], max_length=6, null=True, verbose_name='Órgão'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='condutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crrs', to='crr.condutor'),
        ),
    ]
