# Generated by Django 5.2 on 2025-05-02 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0010_alter_agenteautuador_assinatura_agente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crr',
            name='condutor',
        ),
        migrations.AddField(
            model_name='condutor',
            name='crr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='condutores', to='crr.crr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condutor',
            name='habilitacao_condutor',
            field=models.CharField(blank=True, max_length=11, verbose_name='Habilitação do Condutor'),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='nome_condutor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome do Condutor'),
        ),
    ]
