# Generated by Django 5.2 on 2025-05-02 12:13

import crr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0012_alter_agenteautuador_usuario_alter_condutor_uf_cnh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemcrr',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=crr.models.upload_path, verbose_name='Imagem da Remoção'),
        ),
    ]
