# Generated by Django 5.2 on 2025-05-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0013_alter_imagemcrr_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crr',
            name='matricula_agente',
        ),
        migrations.AddField(
            model_name='crr',
            name='usuario_agente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='crrs', to='crr.agenteautuador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crr',
            name='agente_autuador',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agente autuador'),
        ),
    ]
