# Generated by Django 5.2 on 2025-05-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0014_remove_crr_matricula_agente_crr_usuario_agente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crr',
            old_name='usuario_agente',
            new_name='usuario',
        ),
    ]
