# Generated by Django 5.2 on 2025-05-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0015_rename_usuario_agente_crr_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crr',
            name='usuario',
        ),
        migrations.AddField(
            model_name='crr',
            name='matricula_agente',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agente autuador'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='agente_autuador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crrs', to='crr.agenteautuador'),
        ),
    ]
