# Generated by Django 5.2 on 2025-05-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crr', '0016_remove_crr_usuario_crr_matricula_agente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crr',
            name='numero_crr',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='número do crr'),
        ),
    ]
